// ─────────────────────────────────────────────────────────────────────────────
// Minimal ABIs for the third-party contracts the LP panel talks to.
//
// These are NOT ours, so they are hand-written rather than generated by
// `scripts/extractAbis.js` — that script only walks Tosh artifacts.  Keep these
// trimmed to exactly what the panel calls; a fuller ABI is dead weight in the
// client bundle and invites drift.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * PancakeSwap Infinity CLPositionManager.
 *
 * `modifyLiquidities` is the single mutating entry point: it takes an
 * abi-encoded `(bytes actions, bytes[] params)` payload where `actions` is a
 * packed byte string of `Actions` opcodes.  See `CL_ACTIONS` in contracts.ts
 * — the opcode numbers survived the port; the PoolKey they wrap did not.
 */
export const POSM_ABI = [
  {
    type: 'function',
    name: 'modifyLiquidities',
    stateMutability: 'payable',
    inputs: [
      { name: 'unlockData', type: 'bytes' },
      { name: 'deadline', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getPoolAndPositionInfo',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [
      {
        name: 'poolKey',
        type: 'tuple',
        components: [
          { name: 'currency0', type: 'address' },
          { name: 'currency1', type: 'address' },
          { name: 'hooks', type: 'address' },
          { name: 'poolManager', type: 'address' },
          { name: 'fee', type: 'uint24' },
          { name: 'parameters', type: 'bytes32' },
        ],
      },
      { name: 'info', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getPositionLiquidity',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: 'liquidity', type: 'uint128' }],
  },
  {
    type: 'function',
    name: 'ownerOf',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { name: 'from', type: 'address', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'id', type: 'uint256', indexed: true },
    ],
  },
] as const

/** Infinity CLPoolManager — the read-only surface V4's StateView used to be. */
export const CL_POOL_ABI = [
  {
    type: 'function',
    name: 'getSlot0',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'bytes32' }],
    outputs: [
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'tick', type: 'int24' },
      { name: 'protocolFee', type: 'uint24' },
      { name: 'lpFee', type: 'uint24' },
    ],
  },
  {
    type: 'function',
    name: 'getLiquidity',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'bytes32' }],
    outputs: [{ name: 'liquidity', type: 'uint128' }],
  },
] as const

/**
 * The permission bitmap `PoolKey.parameters` has to repeat. Read off the hook,
 * never typed: `CLPoolManager.initialize` compares the two and reverts on
 * mismatch, so a hard-coded copy is a second source of truth for a value the
 * chain already publishes.
 */
export const HOOKS_BITMAP_ABI = [
  {
    type: 'function',
    name: 'getHooksRegistrationBitmap',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint16' }],
  },
] as const

/**
 * Permit2 `IAllowanceTransfer`.
 *
 * posm never calls `transferFrom` on the token directly — it goes through
 * Permit2, so a first-time LP needs BOTH a normal ERC-20 approval to Permit2
 * and a Permit2 allowance granted to posm.
 */
export const PERMIT2_ABI = [
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [
      { name: 'amount', type: 'uint160' },
      { name: 'expiration', type: 'uint48' },
      { name: 'nonce', type: 'uint48' },
    ],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint160' },
      { name: 'expiration', type: 'uint48' },
    ],
    outputs: [],
  },
] as const
